name: CI

on:
  pull_request:
  push:
    branches:
      - "?.x"

jobs:
  composer-json-lint:
    name: "Lint composer.json"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: ${{ matrix.code-coverage }}
          php-version: ${{ matrix.php-version }}
          extensions: zip, xmlreader, dom
          ini-values: zend.assertions=1,error_reporting=-1
          tools: composer-normalize, composer-require-checker, composer-unused

      - name: "Get composer cache directory"
        id: "composercache"
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache dependencies"
        uses: "actions/cache@v3"
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Validate composer.json"
        run: "composer validate --strict"

      - name: "Normalize composer.json"
        run: "composer-normalize --dry-run"

      - name: "composer-require-checker"
        run: "composer-require-checker --config-file=$(realpath .require-checker-config.json)"

      - name: "composer-unused"
        run: "composer-unused"

  tests:
    name: "Tests"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php-version:
          - "8.0"
          - "8.2"
        code-coverage:
          - "none"
        include:
            - os: "windows-latest"
              php-version: "8.1"
              code-coverage: "none"
            - os: "ubuntu-latest"
              php-version: "8.1"
              code-coverage: "pcov"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: ${{ matrix.code-coverage }}
          php-version: ${{ matrix.php-version }}
          extensions: dom, fileinfo, xmlreader, zip
          ini-values: zend.assertions=1,error_reporting=-1

      - name: "Get composer cache directory"
        id: "composercache"
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache dependencies"
        uses: "actions/cache@v3"
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Run tests"
        timeout-minutes: 3
        run: "make test"

      - name: "Gather base branch for diff"
        if: ${{ github.event_name == 'pull_request' }}
        run: git fetch origin --no-tags --prune --depth=1 ${{ github.base_ref }} ${{ github.event.pull_request.base.sha }}

      - name: "Infection on DIFF"
        if: ${{ github.event_name == 'pull_request' }}
        timeout-minutes: 10
        run: make code-coverage INFECTION_ARGS="--logger-github"
        env:
          BASE_BRANCH: origin/${{ github.base_ref }}
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}

      - name: "Infection on complete code base"
        if: ${{ github.event_name != 'pull_request' }}
        timeout-minutes: 10
        run: "vendor/bin/infection --ansi --threads=$(nproc) --skip-initial-tests --coverage=coverage"
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}

  coding-standards:
    name: "Coding Standards"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: ${{ matrix.php-version }}
          extensions: zip, xmlreader, dom
          ini-values: zend.assertions=1,error_reporting=-1

      - name: "Get composer cache directory"
        id: "composercache"
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache dependencies"
        uses: "actions/cache@v3"
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Run PHP-CS-Fixer"
        run: "vendor/bin/php-cs-fixer fix --verbose --dry-run --diff"

  static-analysis:
    name: "Static Analysis"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: ${{ matrix.php-version }}
          extensions: zip, xmlreader, dom
          ini-values: zend.assertions=1,error_reporting=-1

      - name: "Get composer cache directory"
        id: "composercache"
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache dependencies"
        uses: "actions/cache@v3"
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Run static analysis"
        run: "vendor/bin/phpstan analyse --no-progress --error-format=github"

  benchmarks:
    name: "Benchmarks"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.1"
        bench:
          - "CsvReaderBench"
          - "CsvWriterBench"
          - "OdsReaderBench"
          - "OdsWriterBench"
          - "XlsxReaderInlineBench"
          - "XlsxReaderSharedBench"
          - "XlsxWriterInlineBench"
          - "XlsxWriterSharedBench"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: ${{ matrix.php-version }}
          extensions: zip, xmlreader, dom
          ini-values: zend.assertions=1,error_reporting=-1

      - name: "Get composer cache directory"
        id: "composercache"
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache dependencies"
        uses: "actions/cache@v3"
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: "Remove infection"
        run: "composer remove --no-progress --no-update --no-scripts --dev 'infection/infection'"

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Run benchmarks"
        timeout-minutes: 3
        run: "vendor/bin/phpbench run --report=default --filter ${{ matrix.bench }}"
